# Generated by Django 5.2.5 on 2025-08-25 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(db_index=True, max_length=16, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=8, unique=True)),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='UploadedTimesheetFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.PositiveIntegerField(db_index=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TimesheetEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hours', models.DecimalField(decimal_places=2, max_digits=8)),
                ('hourly_rate', models.DecimalField(decimal_places=2, editable=False, max_digits=8)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='payroll.employee')),
                ('job_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='payroll.jobgroup')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rows', to='payroll.uploadedtimesheetfile')),
            ],
            options={
                'indexes': [models.Index(fields=['date'], name='payroll_tim_date_811c86_idx'), models.Index(fields=['employee', 'date'], name='payroll_tim_employe_7b6d38_idx')],
                'constraints': [models.UniqueConstraint(fields=('file', 'employee', 'date', 'job_group', 'hours'), name='unique_timesheet_entry_row_per_file')],
            },
        ),
    ]
