# Generated by Django 5.2.5 on 2025-08-25 09:51

from django.db import migrations
from decimal import Decimal


def seed_groups(apps, schema_editor):
    JobGroup = apps.get_model("payroll", "JobGroup")
    JobGroup.objects.get_or_create(code="A", defaults={"hourly_rate": Decimal("20.00")})
    JobGroup.objects.get_or_create(code="B", defaults={"hourly_rate": Decimal("30.00")})


def unseed_groups(apps, schema_editor):
    JobGroup = apps.get_model("payroll", "JobGroup")
    JobGroup.objects.filter(code__in=["A", "B"]).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("payroll", "0001_initial"),
    ]

    operations = [migrations.RunPython(seed_groups, reverse_code=unseed_groups)]
